version: '3.0'

services:

  gobexport:
    build: src
    container_name: gobexport
    environment:
      API_HOST: http://api_service:8000

networks:
  default:
    external:
      name: gob-network
