version: '3.8'

services:

  gobexport:
    build:
      context: src
      target: development
    container_name: gobexport
    image: gob_export
    ports:
      - "8168:8000"
    environment:
      ANALYSE_DATABASE_PORT_OVERRIDE: 5432
      ANALYSE_DATABASE_HOST_OVERRIDE: analyse_database
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      GOB_SHARED_DIR: /app/shared
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "gobexport.wsgi"
      UWSGI_CALLABLE: "app"
      UWSGI_PROCESSES: "4"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_THREADS: ""
    env_file: .env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobexport:/app/gobexport
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config

networks:
  default:
    external: true
    name: gob-network

volumes:
  gob-volume:
    external: true
