version: '3.0'

services:

  export_service:
    build: src
    container_name: export_service
    environment:
      API_HOST: http://api_service:8000

networks:
  default:
    external:
      name: gob-network
