version: '3.0'

services:

  gobexport:
    build: src
    container_name: gobexport
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8000
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
    env_file: .env

networks:
  default:
    external:
      name: gob-network
